from grafo2 import Grafo
prueba = Grafo()
prueba.creaNodos(5)
prueba.imprimir("prueba.txt")
prueba.conecta(0.6)
prueba.grafica("prueba.plot")
print(prueba.FloydWarshall())
a = prueba.FordFulkerson(2,6)
print(a)
#prueba.GraficoCajaBigote()
prueba.GraficaErrorB()
